export type ModuleSeedRecord = {
  module: string;
  recordType: string;
  externalId: string;
  name: string;
  status: string;
  sourceRepo: string;
  payload: Record<string, unknown>;
};

export const MODULE_SEED_RECORDS: ModuleSeedRecord[] = [
  { module: "aclienti", recordType: "research_lens", externalId: "default", name: "B2B content research lens", status: "active", sourceRepo: "ACLIENTI", payload: { product: "Evidence-backed content direction", targetCustomer: "Boutique B2B SaaS content agencies", promisedOutcome: "Current customer pain signals converted into content briefs", disqualifiers: "Consumer-only brands, unclear offers, or signals without public sources" } },
  { module: "aclienti", recordType: "signal", externalId: "signal_customer_research", name: "Customer research needs to become usable content", status: "qualified", sourceRepo: "ACLIENTI", payload: { pain: "Generic AI ideas make every client sound the same", sourceTitle: "Making customer research usable for content", sourceUrl: "https://www.reddit.com/r/marketing/", scores: { pain: 5, fit: 5, timing: 5, reach: 4, evidence: 4 } } },
  { module: "aclienti", recordType: "signal", externalId: "signal_voice_of_customer", name: "Teams need a better voice-of-customer workflow", status: "qualified", sourceRepo: "ACLIENTI", payload: { pain: "Teams ask where to find and organize customer language", sourceTitle: "Where do you find voice-of-customer language?", sourceUrl: "https://news.ycombinator.com/", scores: { pain: 4, fit: 5, timing: 4, reach: 3, evidence: 4 } } },
  { module: "aclienti", recordType: "signal", externalId: "signal_content_lead", name: "Companies are hiring for content ownership", status: "new", sourceRepo: "ACLIENTI", payload: { pain: "A content lead hiring trigger can reveal active demand", sourceTitle: "Founding content lead", sourceUrl: "https://www.linkedin.com/jobs/", scores: { pain: 3, fit: 4, timing: 5, reach: 4, evidence: 4 } } },
  { module: "aclienti", recordType: "brief", externalId: "brief_research_workflow", name: "The no-fluff customer research workflow", status: "draft", sourceRepo: "ACLIENTI", payload: { format: "Educational article", angle: "Use the cited observation as opening tension, explain a repeatable process, show one example, and invite comparison", source: "Making customer research usable for content" } },
  { module: "accman", recordType: "account", externalId: "vico_creates", name: "@vico.creates", status: "connected", sourceRepo: "accman", payload: { platform: "TikTok", followers: "24.8K", niche: "Creator productivity" } },
  { module: "accman", recordType: "account", externalId: "vico_studio", name: "Vico Rico Studio", status: "connected", sourceRepo: "accman", payload: { platform: "YouTube", followers: "8.2K", niche: "Behind the scenes" } },
  { module: "accman", recordType: "account", externalId: "thevicoedit", name: "@thevicoedit", status: "connected", sourceRepo: "accman", payload: { platform: "Instagram", followers: "12.6K", niche: "Visual storytelling" } },
  { module: "accman", recordType: "niche", externalId: "creator_productivity", name: "Creator productivity", status: "active", sourceRepo: "accman", payload: { description: "Systems, tools, and routines for making content consistently", accounts: 2 } },
  { module: "accman", recordType: "niche", externalId: "visual_storytelling", name: "Visual storytelling", status: "active", sourceRepo: "accman", payload: { description: "Frameworks for making ordinary moments memorable", accounts: 1 } },
  { module: "accman", recordType: "format", externalId: "ai_ugc_demo", name: "AI UGC product demo", status: "active", sourceRepo: "accman", payload: { notes: "Character introduces the product, demonstrates one use case, and shows the result in a short continuous sequence" } },
  { module: "accman", recordType: "format", externalId: "before_after", name: "Before and after transformation", status: "active", sourceRepo: "accman", payload: { notes: "Show a specific starting problem, introduce the product or process, then reveal the measurable change" } },
  { module: "accman", recordType: "format", externalId: "character_story", name: "Character-led story", status: "idea", sourceRepo: "accman", payload: { notes: "Use a recurring character who faces a relatable situation, makes a discovery, and changes by the end" } },
  { module: "accman", recordType: "trend", externalId: "music_listening_ugc", name: "Girls listening to music UGC", status: "new", sourceRepo: "accman", payload: { platform: "TikTok", notes: "Natural listening moments, reactions, lip-syncs, and mood clips that feel native to short-form video" } },
  { module: "accman", recordType: "trend", externalId: "cinematic_reveal", name: "AI cinematic product reveals", status: "watching", sourceRepo: "accman", payload: { platform: "Multi-platform", notes: "Make ordinary products feel premium through atmosphere, texture, and movement" } },
  { module: "accman", recordType: "plan", externalId: "music_morning", name: "Music that makes a morning better", status: "planned", sourceRepo: "accman", payload: { account: "@vico.creates", format: "Girls listening to music — UGC", date: "2026-08-02" } },
  { module: "accman", recordType: "prompt", externalId: "creative_battlecard", name: "Competitor creative battlecard", status: "saved", sourceRepo: "accman", payload: { category: "Ad research", purpose: "Find winning hooks, visual aesthetics, CTA structures, and gaps without copying competitor scripts" } },
  { module: "clipro", recordType: "source", externalId: "youtube_funnel", name: "How I built a creator funnel in 48 hours", status: "ready", sourceRepo: "clip-ro", payload: { platform: "YouTube", duration: "42:18", clips: 7 } },
  { module: "clipro", recordType: "source", externalId: "twitch_teardown", name: "Live funnel teardown — July session", status: "ready", sourceRepo: "clip-ro", payload: { platform: "Twitch", duration: "1:28:04", clips: 12 } },
  { module: "clipro", recordType: "source", externalId: "founder_interview", name: "Founder interview raw recording", status: "processing", sourceRepo: "clip-ro", payload: { platform: "Upload", duration: "36:51", clips: 0 } },
  { module: "clipro", recordType: "clip", externalId: "clip_views_leads", name: "The reason your views never become leads", status: "ready", sourceRepo: "clip-ro", payload: { score: 94, duration: "00:38", format: "9:16" } },
  { module: "clipro", recordType: "clip", externalId: "clip_owned_audience", name: "One comment can become an owned audience", status: "ready", sourceRepo: "clip-ro", payload: { score: 89, duration: "00:31", format: "9:16" } },
  { module: "reclip", recordType: "workflow", externalId: "source_download", name: "Inspect → playlist → download → ClipRO", status: "ready", sourceRepo: "reclip", payload: { endpoints: ["/api/info", "/api/playlist", "/api/download", "/api/status/:job_id", "/api/file/:job_id", "/api/thumbnail/:job_id"], rightsRequired: true } },
  { module: "autoart", recordType: "artist", externalId: "nova_vale", name: "Nova Vale", status: "active", sourceRepo: "autoart", payload: { niche: "Late-night lo-fi and quiet focus", genre: "lo-fi hip-hop", voice: "Minimal, warm, introspective, precise", cadence: "2 singles per week, 1 EP monthly" } },
  { module: "autoart", recordType: "artist", externalId: "luma_north", name: "Luma North", status: "draft", sourceRepo: "autoart", payload: { niche: "Cinematic ambient for creators", genre: "Ambient cinematic", voice: "Expansive, visual, emotional, direct" } },
  { module: "autoart", recordType: "song", externalId: "afterglow_desk_lamp", name: "Afterglow Desk Lamp", status: "approved", sourceRepo: "autoart", payload: { artist: "Nova Vale", mood: "Mellow, nostalgic, focused, intimate", bpm: 75, key: "F minor", duration: "3:05", useCase: "Study and coding playlists", tags: ["lo-fi", "study", "instrumental", "focus", "night"] } },
  { module: "autoart", recordType: "release", externalId: "midnight_focus_vol_1", name: "Midnight Focus Vol. 1", status: "building", sourceRepo: "autoart", payload: { type: "EP", releaseDate: "2026-07-17", coverStatus: "needs final art", distributor: "DistroKid-ready export" } },
  { module: "autoart", recordType: "promo_campaign", externalId: "afterglow_launch", name: "Afterglow Desk Lamp launch", status: "draft", sourceRepo: "autoart", payload: { channels: ["TikTok", "Reels", "Shorts", "Playlist outreach"], clips: ["Desk lamp turns on, beat drops after the switch click", "One-hour coding session time-lapse", "Rain on window, Rhodes chords enter after three seconds"] } },
  { module: "streamwin", recordType: "live_session", externalId: "default_studio", name: "Vision-aware live studio", status: "draft", sourceRepo: "streamwin", payload: { scenes: 4, destinations: ["Twitch", "YouTube", "TikTok LIVE"], controls: ["mic", "camera", "broadcast", "scene", "automation"] } },
  { module: "streamwin", recordType: "scene", externalId: "cyber_scene", name: "Cyber live scene", status: "ready", sourceRepo: "streamwin", payload: { effects: ["prompt-driven transformation", "AI intensity", "quick effects"] } },
  { module: "streamwin", recordType: "vision_agent", externalId: "event_reactor", name: "Vision event reactor", status: "review", sourceRepo: "streamwin", payload: { detects: ["gestures", "objects", "landmarks", "gameplay", "on-camera events"], controls: ["cooldown", "human override", "emergency stop"] } },
  { module: "masscall", recordType: "use_case", externalId: "ai_receptionist", name: "AI receptionist", status: "idea", sourceRepo: "masscall", payload: { audience: "Dentists, salons, clinics", actions: ["answer calls", "book appointments", "handle FAQs", "speak client language"] } },
  { module: "masscall", recordType: "use_case", externalId: "sales_qualifier", name: "AI sales qualifier", status: "idea", sourceRepo: "masscall", payload: { audience: "Startups and mid-market sales teams", actions: ["qualify inbound leads", "ask questions", "book meetings", "route to CRM"] } },
  { module: "masscall", recordType: "use_case", externalId: "restaurant_orders", name: "Restaurant order-taking agent", status: "idea", sourceRepo: "masscall", payload: { audience: "Restaurants and takeout spots", actions: ["take orders", "upsell", "confirm", "push to POS"] } },
  { module: "masscall", recordType: "router", externalId: "workspace_action_router", name: "Workspace action router", status: "prototype", sourceRepo: "masscall", payload: { apps: ["Calendar", "Gmail", "Slack", "Notion", "Workspace"], safety: "Returns a command proposal; never executes external actions automatically" } }
];
